language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
cache:
  - pip
install:
  - pip install -U setuptools
  - pip install tox-travis
  - pip install -r requirements-dev.txt
script:
  tox
